export const HANDLE_CHANGE_ONE_WORD = 'question/HANDLE_CHANGE_ONE_WORD';
export const HANDLE_CHANGE_IN_DETAIL = 'question/HANDLE_CHANGE_IN_DETAIL';
export const HANDLE_PREVIEW_IMAGE = 'question/HANDLE_PREVIEW_IMAGE';
export const HANDLE_CANCEL_IMAGEVIEW = 'question/HANDLE_CANCEL_IMAGEVIEW';
export const HANDLE_CHANGE_UPLOAD_IMAGE = 'question/HANDLE_CHANGE_UPLOAD_IMAGE';
export const UP_LOAD_IMAGE = 'question/UP_LOAD_IMAGE';
export const CHANGE_PERCENT = 'question/CHANGE_PERCENT';
export const HANDLE_CASCADER_CHANGE = 'question/HANDLE_CASCADER_CHANGE';